server:
  port: 10300


spring:
  application:
    name: business-server

  datasource:
    username: root
    password: "2568898559yY"
    url: jdbc:mysql://sh-cynosdbmysql-grp-lr3zkq1e.sql.tencentcdb.com:23946/elmSpringCloud?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework: debug
    com.Iynew.mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Iynew.po

eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer13000:13000/eureka,http://eurekaServer13001:13001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} 